name: MineSky-Events
version: 1.0.8-BETA
main: minesky.msne.MineSkyEvents
api-version: '1.19'
authors: [BrunoC, Drawn]
load: POSTWORLD
depeend: [WorldGuard, MMOItems]

permissions:
  mineskyevents.reload:
    description: Permission to execute plugin reload.
    default: op
  mineskyevents.give:
    default: op
  mineskyevents.command.event.start:
    description: Permission to initiate an event.
    default: op
  mineskyevents.command.event.set:
    description: Permission to set some information for the event.
    default: op
  mineskyevents.bypass.join:
    description: Permission to bypass the automatic teleportation system to events
    default: op
  mineskyevents.command.event.anunciar:
    description: Permission event message.
    default: op
  mineskyevents.command.event.kick:
    description: Permission to remove a participant from the event.
    default: op
  mineskyevents.command.event.blacklist:
    description: Permission to add or remove a player from the event blacklist.
    default: op
  mineskyevents.command.event.finalizar:
    description: ...
    default: op
  mineskyevents.notify.enabled:
    description: ...
    default: op
  mineskyevents.notify.moderation:
    description: Permission to receive kick notifications from events.
    default: false
  mineskyevents.notify.restored:
    description: Permission to be notified when the Spleef arena has been restored.
    default: false
  mineskyevents.notify.blacklist:
    description: Permission to receive kick notifications from events.
    default: false
  mineskyevents.notify.leave:
    description: Permission to be alerted when a player leaves the event world.
    default: false
  mineskyevents.bypass.all:
    description: Permission to bypass all plugin features.
    default: false
    children:
      mineskyevents.bypass.join: true
  mineskyevents.notify.all:
    description: Permission to have access to all notifications.
    default: false
    children:
      mineskyevents.notify.enabled: true
      mineskyevents.notify.moderation: true
      mineskyevents.notify.blacklist: true
      mineskyevents.notify.leave: true
      mineskyevents.notify.restored: true
  mineskyevents.admin:
    description: Plugin admin permission.
    default: op
    children:
      mineskyevents.reload: true
      mineskyevents.give: true
      mineskyevents.command.event.start: true
      mineskyevents.command.event.set: true
      mineskyevents.command.event.kick: true
      mineskyevents.command.event.blacklist: true
      mineskyevents.command.event.finalizar: true